### ISSUE TITLE
Implement "Deploy to Heroku" button

### ISSUE THREAD

**Issue by gokaygurcan** [gokaygurcan/analytics#12]
Details here: https://devcenter.heroku.com/articles/heroku-button

**Comment by yunchih** [comment]
Do we need some kind of `else if(brand === 'heroku') ....`.  Or simply put the image in the public folder?

**Comment by gokaygurcan** [comment]
Hello @Akim95 ,
Thanks for the button! I believe this is a nice improvement for everyone.

Hey @yunchih , 
I couldn't get what did you meant with the else statement?
