### ISSUE TITLE
Implement "OpenShift Deploy" button

### ISSUE THREAD

**Issue by gokaygurcan** [gokaygurcan/analytics#13]
Details here: https://blog.openshift.com/updated-openshift-deploy-buttons/

**Comment by KameronArgis** [comment]
Hello @gokaygurcan ! 
Is it ok if i do it ?

**Comment by gokaygurcan** [comment]
Hi @KameronArgis , 
Since there's no volunteer to pick this up, I think it's totally fine if you can pick. 

Good luck!
