### ISSUE TITLE
Create a homepage

### ISSUE THREAD

**Issue by gokaygurcan** [gokaygurcan/analytics#3]
Currently, it redirects to my homepage which is not useful. It'd be nice to have a nice and clean homepage that shows the usages and examples, etc.

**Comment by akankshajsh** [comment]
@gokaygurcan Is there a design for the homepage?

**Comment by raj-maurya** [comment]
Hi @gokaygurcan,

Can you guide, from where I can get the "examples" and etc. to show on the homepage?

**Comment by gokaygurcan** [comment]
Hello @akankshajsh and @raj-maurya,
It's really nice to hear from someone, thanks a lot, really.

Sadly, there's no design but I'm open to any suggestions at this point. If you have something already, I'm totally OK with that. 

I'll provide some examples and more usages later today (probably in an hour) and update the issue.

**Comment by gokaygurcan** [comment]
Hello again,

I changed the badges and added couple of more examples. You can find them in README.md file.

Thanks.

**Comment by raj-maurya** [comment]
@gokaygurcan 

I am getting the error while running the "npm start" in the terminal.
It was running and redirecting to your page, just before you updated the README.md  file.

Please look at the error in file (node index.js) in the screenshot:
![screenshot from 2016-10-05 02 11 39](https://cloud.githubusercontent.com/assets/9070249/19091818/c2b3ab1a-8aa1-11e6-97b6-0d36a79e104f.png)

**Comment by gokaygurcan** [comment]
Hello @raj-maurya,

That's because, there's already another app running and using the port. 

You can type `lsof -Pnl +M -i6` to find out which PID is using that port and then kill it. 

```
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    16054     1000   10u  IPv6  94916      0t0  TCP *:6598 (LISTEN)
```

You'll see an output like this, just type `sudo kill 16054`  (replace this one with yours of course) and run `npm start` again. 

Sorry for complications, I'm still thinking a stable way for it. Probably I'll consider @heroku or @openshift but who knows.

**Comment by raj-maurya** [comment]
Thanks! @gokaygurcan

**Comment by raj-maurya** [comment]
@gokaygurcan 

Screenshots for the homepage:
![screenshot from 2016-10-05 13 19 39](https://cloud.githubusercontent.com/assets/9070249/19105246/b0048d38-8afe-11e6-9e46-27d7614bbc9f.png)

![screenshot from 2016-10-05 13 20 00](https://cloud.githubusercontent.com/assets/9070249/19105256/bcefd282-8afe-11e6-9ac1-892aa4e15f9a.png)
![screenshot from 2016-10-05 13 20 18](https://cloud.githubusercontent.com/assets/9070249/19105265/c4f29a28-8afe-11e6-81b7-f397764a93f6.png)

**Comment by gokaygurcan** [comment]
Closing this because we have https://gokaygurcan.github.io/analytics/ now. Thanks.
