### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by gokaygurcan** [gokaygurcan/analytics#4]
It'd be really nice if this project has its own logo. Then we can update the favicon and maybe use the logo on the homepage after #3 's done.

**Comment by RobAWilkinson** [comment]
I can do this, any vibe or theme that you want to keep in mind?

**Comment by gokaygurcan** [comment]
Hello @RobAWilkinson ,
It'd be nice if it'll represent its purpose: statistics. Maybe something like a bar chart or pie chart. 
Thanks!

**Comment by jwasham** [comment]
I saw this was still unclosed so I created a pull request.

**Comment by gokaygurcan** [comment]
Hello @jwasham,

Thanks for the logo, I'll merge it now. 
It might change in the future, so don't feel bad about this please.
